### ISSUE TITLE
java gem extension

### ISSUE THREAD

**Issue by prees1** [rawr/rawr#35]
I am trying to package up my app with some gem dependencies. I am able to package it up and source the required gems except for one. The nokogiri gem has a java extension in the 'ext' directory. When I include this gem in the package it breaks the rawr compilation:

```
mkdir -p packaging/migrate/classes/java
javac -source 1.7 -target 1.7 -cp lib/java/jruby-complete.jar:lib/migrate -sourcepath lib/migrate -d packaging/migrate/classes/java lib/migrate/org/monkeybars/rawr/Main.java
warning: [options] bootstrap class path not set in conjunction with -source 1.7
Note: lib/migrate/org/monkeybars/rawr/Main.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning
javac -source 1.7 -target 1.7 -cp lib/java/jruby-complete.jar:lib/migrate -sourcepath lib/migrate -d packaging/migrate/classes/java lib/migrate/org/nokogiri/EncodingHandler.java
warning: [options] bootstrap class path not set in conjunction with -source 1.7
lib/migrate/org/nokogiri/EncodingHandler.java:35: error: package nokogiri.internals does not exist
import static nokogiri.internals.NokogiriHelpers.getNokogiriClass;
                                ^
lib/migrate/org/nokogiri/EncodingHandler.java:35: error: static import only from classes and interfaces
import static nokogiri.internals.NokogiriHelpers.getNokogiriClass;
^
lib/migrate/org/nokogiri/EncodingHandler.java:85: error: cannot find symbol
            getNokogiriClass(ruby, "Nokogiri::EncodingHandler"),
            ^
  symbol:   method getNokogiriClass(Ruby,String)
  location: class EncodingHandler
3 errors
1 warning
rake aborted!
Command failed with status (1): [javac -source 1.7 -target 1.7 -cp lib/java...]
org/jruby/RubyProc.java:289:in `call'
```

So the java portion of nokogiri is not being handled correctly here. My question is, is there a specific place I should put this part of nokogiri or is there a path I can set in the configuration to properly source this directory?

I have tried a few different possibilities but nothing has seemed to change the above results. I have also read several posts on how to properly include gems with rawr and none that I have seen have mentioned a scenario like this. 

Any insight would be greatly appreciated!

Thanks

PS. I tried to post this to the [google group](https://groups.google.com/forum/#!forum/rawr-lib) but my posts did not seem to show up. I apologize if this is the wrong spot or if there is simply a delay or review on the other listing.

**Comment by Neurogami** [comment]
The Google Group has some anti-spam thing in place, where all first-posts are held for approval.  I didn't get  a chance to approve the messages until now.

When you install the java version of Nokogiri, does it not give you a usable jar file? I installed the gem and in the gem installation folder, in nokogiri-1.6.7.2-java/lib, there are a number of jars.  

Rawr shouldn't be trying to compile any source java for this gem (I would think). You should be able to unpack the gem to a local project folder and reference that from your application.

I don't think you need the ext folder, just the lib.   Rawr is essentially invoking jruby against a main class  and a custom $:


I see that `gem unpack nokogiri` gives you *everything*, but I think all you need is lib/, and to load the jar files there.

But if rawr finds java files in it's path it will try to compile them.

**Comment by prees1** [comment]
Ok I thought that might be the case. It is likely better for all if this discussion continues on the Google Group as this is definitely not an issue with rawr but more an issue with how I should be using it.

[Here is a link](http://jamesbritt.com/posts/using-a-gem-with-rawr.html) to the same discussion on there.

**Comment by Neurogami** [comment]
One last comment: Your posts to the rawr group were not going through because you are not a member of the group.    Otherwise they end up in the moderation queue.
